trigger:
- main

pool:
  vmImage: 'windows-latest'  # Change this to use a Windows agent

variables:
  keyVaultName: 'Test123-AKV'
  secretName: 'TestSecret'

stages:
- stage: FetchAndPrintSecret
  jobs:
  - job: FetchSecret
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'SPN-AKV'
        KeyVaultName: $(keyVaultName)
        SecretsFilter: $(secretName)
        RunAsPreJob: true

    - script: |
        echo "The secret value is: $(your-secret-name)"
      displayName: 'Print secret value'
      shell: powershell  # Ensure the script runs in PowerShell on Windows

