trigger:
- main

pool:
  name: 'win-agent-pool'  # Use the self-hosted agent pool

variables:
  keyVaultName: 'Test123-AKV'
  secretName: 'TestSecret'

stages:
- stage: FetchAndPrintSecret
  jobs:
  - job: FetchSecret
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'SPN-AKV'
        KeyVaultName: $(keyVaultName)
        SecretsFilter: $(secretName)
        RunAsPreJob: true

    - script: |
        echo "The secret value is: $(TestSecret)"  # Use the secret name directly
      displayName: 'Print secret value'
